// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Environment is an autogenerated mock type for the Environment type
type Environment struct {
	mock.Mock
}

// GetString provides a mock function with given fields: _a0
func (_m *Environment) GetString(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsSet provides a mock function with given fields: _a0
func (_m *Environment) IsSet(_a0 string) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetConfigFile provides a mock function with given fields: _a0
func (_m *Environment) SetConfigFile(_a0 string) {
	_m.Called(_a0)
}
