name: edgex-cli
base: core20
type: app
adopt-info: version
summary: A command-line client for EdgeX Foundry
description: |
  A command-line client for EdgeX Foundry.

grade: stable
confinement: strict

apps:
  edgex-cli:
    adapter: none
    command: bin/edgex-cli
    command-chain:
      - bin/edgex-cli-wrapper.sh
    plugs: [home, network]

parts:
  version:
    plugin: nil
    # we need to include git, in case we are building the minimal-snap-build
    build-packages:
      - git
    # as with static-packages part, the source dir is unrelated to this part and is used
    # since it changes rarely and therefore will not trigger a new pull
    source: snap/local/runtime-helpers
    override-pull: |
      cd $SNAPCRAFT_PROJECT_DIR
      GIT_VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      if [ -z "$GIT_VERSION" ]; then
        GIT_VERSION="0.0.0"
      fi
      snapcraftctl set-version ${GIT_VERSION}

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

  edgex-cli:
    source: .
    plugin: make 
    build-snaps:
      - go/1.17/stable 
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make tidy
      make build
      install -DT "./bin/edgex-cli" "$SNAPCRAFT_PART_INSTALL/bin/edgex-cli"
      install -DT "./Attribution.txt" "$SNAPCRAFT_PART_INSTALL/usr/share/doc/edgex-cli/Attribution.txt"
      install -DT "./LICENSE" "$SNAPCRAFT_PART_INSTALL/usr/share/doc/edgex-cli/LICENSE" 

