name: edgex-cli
base: core20
type: app
adopt-info: metadata

grade: stable
confinement: strict

apps:
  edgex-cli:
    adapter: none
    command: bin/edgex-cli
    command-chain:
      - bin/edgex-cli-wrapper.sh
    plugs: [home, network]

parts:
  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

  edgex-cli:
    after: [metadata]
    source: .
    plugin: make 
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      make tidy
      make build
      install -DT "./bin/edgex-cli" "$SNAPCRAFT_PART_INSTALL/bin/edgex-cli"
      install -DT "./Attribution.txt" "$SNAPCRAFT_PART_INSTALL/usr/share/doc/edgex-cli/Attribution.txt"
      install -DT "./LICENSE" "$SNAPCRAFT_PART_INSTALL/usr/share/doc/edgex-cli/LICENSE" 

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-cli.metainfo.xml] 

